### PR TITLE
Add tox

### PR DESCRIPTION
**Pull request by medecau**
This pull-request adds a tox config file.

Tox is a test automation tool that creates dedicated virtualenvs before running the tests.
Read more about tox: https://tox.readthedocs.io/en/latest/

*You can speed up the tests by using detox in place of tox.*

### CODE REVIEW

**Comment by Digenis** [comment]
Hi @medecau, welcome to fn.py.
Can you also update ".travis.yml"?

**Comment by medecau** [comment]
@Digenis the change is done but the tests were failing on python 3.2.

Tox uses virtualenv to set up the different environments to run tests.
Virtualenv dropped support for python 3.2 earlier this year on version 14.
See: https://virtualenv.pypa.io/en/stable/changes/

**Comment by Digenis** [comment]
Python3.2 seems troublesome.
I don't know why one would still use it, I'm ok with dropping it.

I think it's reasonable to support 3.3 and higher
for packages targeting pypy3 compatibility.

**Comment by jacobbridges** [comment]
I'm also in favor of dropping Python 3.2 compatibility. According to a [Python usage survey in 2014](http://www.randalolson.com/2015/01/30/python-usage-survey-2014/), version 3.2 has about as much of the community as Python 2.5, which is no longer supported by most libraries.

graph

Should we open a new pull request to drop 3.2 support?

**Comment by Digenis** [comment]
@medecau did it already to fix the build

**Pull request merged**
